### PR TITLE
Update kube-thanos to get anti-affinity for queriers and receivers

### PR DESCRIPTION
**Pull request by metalmatze**
/cc @squat @kakkoyun

### CODE REVIEW

**Comment by brancz** [comment]
Is it possible to add node region to this in a generic way?

**Comment by metalmatze** [comment]
@brancz, not sure if there's a standard for these labels on nodes. I'd say spreading out across nodes is a good default. There might be people only running in a single region entirely.

**Comment by squat** [comment]
Yes there are standardized labels for both zone and region. These are discussed in the well-known labels doc from the k8s documentation:

https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/#topologykubernetesiozone

**Comment by brancz** [comment]
Very cool! I wasn’t aware of it! In that case we should additionally add preferred at scheduling and ignored at runtime for zone mode affinity.

**Pull request merged**
