### PR TITLE
thanos/compactor: Add PVC, remove jaeger

### PR DESCRIPTION
**Pull request by kakkoyun**
- Remove unused jaeger-agent
- Add PVC for compactor

### CODE REVIEW

**Comment by bwplotka** [comment]
Let's first investigate what is using disk space. Ability of execing into compactor would be nice

**Comment by metalmatze** [comment]
Overall the changes look good to me.

**Comment by kakkoyun** [comment]
cc @aditya-konarde

**Comment by bwplotka** [comment]
Thanks @kakkoyun !

**Pull request merged**
