### PR TITLE
Add SLOs rules for Observatorium

### PR DESCRIPTION
**Pull request by metalmatze**
Using https://github.com/metalmatze/slo-libsonnet to generate SLOs from high level definition.

### CODE REVIEW

**Comment by brancz** [comment]
slick :+1: anything in particular you're looking for or waiting for why the PR is a draft?

**Comment by brancz** [comment]
Sorry about that, misclick.

**Comment by metalmatze** [comment]
The SLO-libsonnet is currently under heavy development and constantly changes. Hourly during work hours I'd say.
But, with the `all` branch created, I simply merge the individual branches into it, so that previous commit hashes shouldn't disappear anymore, which was my biggest concert for this to a draft.

**Comment by brancz** [comment]
ack, this already looks really good, let us know when you want a thorough review! :)

**Comment by metalmatze** [comment]
This is ready for a first review.

**Comment by brancz** [comment]
nice! :+1:

**Pull request merged**
