### PR TITLE
Add termination grace period to Thanos pods

### PR DESCRIPTION
**Pull request by kakkoyun**
This PR adds similar changes as in https://github.com/thanos-io/kube-thanos/pull/65, since Observatorium runs master version of Thanos.

### CODE REVIEW

**Comment by brancz** [comment]
Feel free to merge at your own discretion.

**Comment by metalmatze** [comment]
These changes should be done upstream with kube-thanos. Any reason not to do that?

**Comment by kakkoyun** [comment]
@metalmatze Already done, that's in the issue https://github.com/thanos-io/kube-thanos/pull/65 that I've referred until it gets released this should do the work.

**Comment by brancz** [comment]
Do we have v0.9.0 deployed?

**Comment by kakkoyun** [comment]
@brancz Not, yet. This is not an urgent one, I'm just doing the grunt work.

**Comment by kakkoyun** [comment]
Blockers:
1) CI fails already fixed in another issue, it won't be a problem when we merge it #122, before this.
2) Only safe to run on Thanos v0.9.0 and above :)

**Pull request merged**
