### PR TITLE
Remove telemetric scripts

### PR DESCRIPTION
**Pull request by rollandf**
Not needed as Openshift environment was removed

### CODE REVIEW

**Comment by rollandf** [comment]
@krasi-georgiev @kakkoyun

**Comment by kakkoyun** [comment]
@krasi-georgiev Could you merge this when we move them?

**Comment by krasi-georgiev** [comment]
yes just checking why are there 2 script for this. After checking with @brancz he suggested that only the script that adds new whitelisted metrics without removing old ones should be used.

**Comment by krasi-georgiev** [comment]
Here is the new script. The PR also includes the new generated whitelisted values.

https://gitlab.cee.redhat.com/observatorium/configuration/merge_requests/36/diffs

Please review and lets merge:

cc @brancz @lilic @metalmatze

**Pull request merged**
