### PR TITLE
Upgrade Observatorium API GW

### PR DESCRIPTION
**Pull request by kakkoyun**
Upgrade Observatorium API GW to its latest version

cc @nmagnezi

### CODE REVIEW

**Comment by brancz** [comment]
lgtm on green

**Comment by kakkoyun** [comment]
I need to check why the operator fails.

**Comment by nmagnezi** [comment]
You should also update the image tag in the CR example/core_v1alpha1_observatorium.yaml

**Comment by rollandf** [comment]
It would be great to have the CR example generated from https://github.com/observatorium/configuration/blob/master/environments/base/default-config.libsonnet

**Pull request merged**
