### PR TITLE
Jsonnet vendoring

### PR DESCRIPTION
**Pull request by rollandf**

### CODE REVIEW

**Comment by rollandf** [comment]
Fixes #239

**Comment by rollandf** [comment]
@brancz PTAL

**Comment by brancz** [comment]
As Kemal noted this repo is intended to be used as a dependency of downstream usages, this maens that `jsonnetfile.lock.json` should not be in the root of the directory but rather per environment. We can easily achieve this with local directory dependencies.

**Comment by rollandf** [comment]
> As Kemal noted this repo is intended to be used as a dependency of downstream usages, this maens that `jsonnetfile.lock.json` should not be in the root of the directory but rather per environment. We can easily achieve this with local directory dependencies.

Following up this: 
so there will be a sonnetfile.json under environments/base and another one under environments/dev?
Then we could have the vendor dir under each?
for the operator we could copy the vendor dir from base in the docker file.

Will this work?

**Pull request closed without merging**
