### PR TITLE
Consume authorize_url from Secret

### PR DESCRIPTION
**Pull request by maorfr**
This PR intends to take the authorization URL out of the template and into the telemeter-server Secret.

Please let me know if you think this is a good idea!

Can you also point out where I'm missing a change in jsonnet?
Update: depends on https://github.com/openshift/telemeter/pull/288

Thanks!

### CODE REVIEW

**Comment by metalmatze** [comment]
The changes would need to be made in this file in the Telemeter repository:
https://github.com/openshift/telemeter/blob/master/jsonnet/telemeter/server/kubernetes.libsonnet
With the changes being merged over there we can then update the Telemeter dependency in this repository by running `jb update`.

**Comment by maorfr** [comment]
wondering what i'm doing wrong @metalmatze

**Comment by metalmatze** [comment]
Updating all jsonnet dependencies broke the current jsonnet stack.

**Comment by maorfr** [comment]
I can update only telemeter manually. How is the hash calculated?

**Comment by maorfr** [comment]
@metalmatze care to take a look again?

**Comment by metalmatze** [comment]
I am still not sure if we really want this in our templates. @squat what do you think?

**Comment by squat** [comment]
We discussed with Maor a few weeks ago. It is not a change we like but, due to details/limitations of the saas-herder stack [1], it is required in order to enable deploying configmaps and other assets from outside of the app-interface repo. For that reason I think that the benefit outweighs the cost :/

[1]  the tooling requires all https urls to be in a secret, as it incorrectly assumes that it is sensitive information.

**Comment by maorfr** [comment]
these changes are now in master, closing this one.

**Pull request closed without merging**
