### PR TITLE
rename api gateway to just api

### PR DESCRIPTION
**Pull request by krasi-georgiev**
Signed-off-by: Krasi Georgiev <8903888+krasi-georgiev@users.noreply.github.com>

### CODE REVIEW

**Comment by brancz** [comment]
cc @metalmatze @squat

**Comment by squat** [comment]
:thinking: I could have sworn I already lgtm'd this yesterday

**Comment by krasi-georgiev** [comment]
>  I could have sworn I already lgtm'd this yesterday

That was in the obs/obs repo. Too many repos!

**Comment by squat** [comment]
:see_no_evil:

**Pull request merged**
